---
title: "TIdy Data"
author: "Elaine Yanxi Chen"
date: "2022-09-27"
output: html_document
---

```{r}
library(tidyverse)
options(tibble.print_min = 5)
```

### `pivot_longer`

We will first read in the pulse data and clean the data with the janitor function.
We can also remove the bdi_score prefix from the visit variable. Use names_prefix to drop it.

```{r}
pulse_df = haven::read_sas("data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    values_to = "bdi",
    names_prefix = "bdi_score_"
  ) %>% 
  mutate(
    visit = replace(visit, visit == "bl", "00m"),
    visit = factor(visit)
  ) %>% 
  arrange(id, visit)
```

### Learing Assessment

```{r}
litters_df = read_csv("data/FAS_litters.csv",
                            col_types = "ccddiiii") %>% 
  janitor::clean_names() %>% 
  select(litter_number, gd0_weight, gd18_weight) %>% 
  pivot_longer(
    gd0_weight:gd18_weight,
    names_to = "gd",
    values_to = "weight",
  ) %>% 
 mutate(gd = recode(gd, "gd0_weight" = 0, "gd18_weight" = 18))
```


